# Generated by Django 4.1.5 on 2023-07-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('identity', models.AutoField(primary_key=True, serialize=False)),
                ('decs', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialisation', models.CharField(choices=[('Criminal', 'Criminal'), ('Labour', 'Labour'), ('Intellectual Property', 'Intellectual Property'), ('Corporate', 'Corporate')], max_length=200)),
                ('rating', models.FloatField(default=3)),
                ('no_of_ratings', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consult.customer'),
        ),
        migrations.AddField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consult.lawyer'),
        ),
    ]
